import * as DesignSystem from 'ds';

export default {
  Flex: DesignSystem.Flex,
  Box: DesignSystem.Box,
  h1: DesignSystem.H1,
  h2: DesignSystem.H2,
  h3: DesignSystem.H3,
  h4: DesignSystem.H4,
  h5: DesignSystem.H5,
  h6: DesignSystem.H6,
  p: DesignSystem.Text,
  blockquote: DesignSystem.Blockquote,
  cite: DesignSystem.Cite,
  ul: DesignSystem.List,
  ol: DesignSystem.OrderedList,
  li: DesignSystem.ListItem,
  // pre:	Pre,
  // code:	Code,
  // em:	Emphasis,
  // strong:	Strong,
  // delete:	Delete,
  // code:	InlineCode,
  // hr:	Break,
  a: DesignSystem.Link,
  // img:	Image,
};
